cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    # 加入购物车
    path('add_cart/', views.add_cart, name='add_cart'),
    # 购物车数量的刷新（添加在父模板里面）
    path('cart_num/', views.cart_num, name='cart_num'),
    # 购物车
    path('cart/', views.cart, name='cart'),
    # 购物车计算价格
    path('cart_price/', views.cart_price, name='cart_price'),

    # 修改购物车中的数量/选择状态
    path('change_cart/', views.change_cart, name='change_cart'),

    #删除购物车中的商品
    path('del_cart/<int:id>/',views.del_cart,name='del_cart'),
]

fresh_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static

from fresh_shop.settings import MEDIA_URL, MEDIA_ROOT

from goods import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # 导入应用
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('goods/', include(('goods.urls', 'goods'), namespace='goods')),
    path('order/', include(('order.urls', 'order'), namespace='order')),
    path('user/', include(('user.urls', 'user'), namespace='user')),
    path('', views.index)
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('detail/<int:id>/', views.detail, name='detail'),
    # 查看更多
    path('my_list/<int:id>/', views.my_list, name='my_list'),
    # 搜索
    path('goods_search/', views.goods_search, name='goods_search')
]

order/urls.py
from django.urls import path

from order import views

urlpatterns = [
    #结算功能
    path('place_order/',views.place_order,name='place_order'),

    # 创建订单
    path('order/',views.order,name='order'),
    # 全部订单
    path('user_order/',views.user_order,name='user_order')
]

user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    # 收货地址
    path('user_site/', views.user_site, name='user_site'),

    # 个人中心
    path('user_info/',views.user_info,name='user_info')
]

cart/models.py
from django.db import models

from goods.models import Goods
from user.models import User


class ShoppingCart(models.Model):
    """
    购物车
    """
    user = models.ForeignKey(User, verbose_name='用户', on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, verbose_name='商品', on_delete=models.CASCADE)
    nums = models.IntegerField(default=0, verbose_name='数量')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')
    is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'f_shopping_cart'

goods/models.py
from django.db import models


class GoodsCategory(models.Model):
    """
    Goods类别
    """
    CATEGORY_TYPE = (
        (1, '新鲜水果'),
        (2, '海鲜水产'),
        (3, '猪牛羊肉'),
        (4, '禽类蛋品'),
        (5, '新鲜蔬菜'),
        (6, '速冻食品'),
    )
    category_type = models.IntegerField(choices=CATEGORY_TYPE, verbose_name='类目级别')
    category_front_image = models.ImageField(upload_to='goods/images/', null=True, blank=True, verbose_name='封面图')

    class Meta:
        db_table = 'f_goods_category'


class Goods(models.Model):
    """
    商品
    """
    category = models.ForeignKey(GoodsCategory, verbose_name='商品类目', on_delete=models.CASCADE)
    name = models.CharField(max_length=100, verbose_name='商品名')
    goods_sn = models.CharField(max_length=50, default='', verbose_name='商品唯一货号')
    click_nums = models.IntegerField(default=0, verbose_name='点击数')
    sold_nums = models.IntegerField(default=0, verbose_name='销售量')
    fav_nums = models.IntegerField(default=0, verbose_name='收藏数')
    goods_nums = models.IntegerField(default=0, verbose_name='商品库存')
    market_price = models.FloatField(default=0, verbose_name='市场价格')
    shop_price = models.FloatField(default=0, verbose_name='本店价格')
    goods_brief = models.CharField(max_length=500, verbose_name='商品简短描述')
    goods_desc = models.TextField(null=True)
    ship_free = models.BooleanField(default=True, verbose_name='是否承担运费')
    goods_front_image = models.ImageField(upload_to='goods/images/', null=True, blank=True, verbose_name='封面图')
    is_new = models.BooleanField(default=False, verbose_name='是否新品')
    is_hot = models.BooleanField(default=False, verbose_name='是否热销')
    add_time = models.DateTimeField(auto_now_add=True, verbose_name='添加时间')

    class Meta:
        db_table = 'f_goods'

cart/views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt

from cart.models import ShoppingCart
from goods.models import Goods


def add_cart(request):
    if request.method == 'POST':
        # 接收商品id 值和数量num
        # 组装存储的商品格式：[goods_id,num,is_select]
        # 组装多个商品格式:[[goods_id,num,is_select],[goods_id,num,is_select]]
        goods_id = int(request.POST.get('goods_id'))
        goods_num = int(request.POST.get('goods_num'))
        goods_list = [goods_id, goods_num, 1]

        # session_goods类型为：[[goods_id,num,is_select],[goods_id,num,is_select]]
        session_goods = request.session.get('goods')
        if session_goods:

            # 1.添加重复的商品，则修改数量num
            flag = True
            for se_goods in session_goods:
                if se_goods[0] == goods_id:
                    se_goods[1] += goods_num
                    flag = False

            # 如果还是为True，说明未执行上一步，说明商品未在购物车中
            # 2.添加的商品不存在于购物车中，则新增
            if flag:
                session_goods.append(goods_list)

            # 最后不管是新增还是修改，都把数据修改到session中
            request.session['goods'] = session_goods
            count = len(session_goods)
        else:
            # 第一次添加购物，需组装购物车中商品格式需要为[[goods_id,num,is_select]]
            request.session['goods'] = [goods_list]
            count = 1

        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart_num(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        if session_goods:
            count = len(session_goods)
        else:
            count = 0
        return JsonResponse({'code': 200, 'msg': '请求成功', 'count': count})


def cart(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        result = []
        if session_goods:
            # 组装返回格式[objects1,objects2...]
            # objects ===> [Goods Object , num , is_select,market_price ]
            for se_goods in session_goods:
                # se_goods为[goods_id,num,is_select]
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                market_price = goods.market_price * se_goods[1]
                # objects ===> [Goods Object , num , is_select,market_price ]
                data = [goods, se_goods[1], se_goods[2], market_price]
                result.append(data)
        return render(request, 'cart.html', {'result': result})


def cart_price(request):
    if request.method == 'GET':
        session_goods = request.session.get('goods')
        # 总的商品件数
        all_total = len(session_goods) if session_goods else 0
        all_price = 0
        is_select_num = 0
        market_price = 0
        for se_goods in session_goods:
            # se_goods为[goods_id,num,is_selelct]
            if se_goods[2]:
                goods = Goods.objects.filter(pk=se_goods[0]).first()
                all_price += goods.market_price * se_goods[1]
                is_select_num += 1
        return JsonResponse({'code': 200, 'msg': '请求成功',
                             'all_total': all_total,
                             'all_price': all_price,
                             'is_select_num': is_select_num,
                             })


@csrf_exempt
def change_cart(request):
    if request.method == 'POST':
        # 修改商品的数量和选择状态
        # 其实就是修改session中商品信息结构为：[goods_id,num,is_selelct]
        print(123456789)
        # 1.获取商品id值和数量或者选择状态
        goods_id = int(request.POST.get('goods_id'))
        goods_num = request.POST.get('goods_num')
        goods_select = request.POST.get('goods_select')
        # 修改
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            if se_goods[0] == goods_id:
                se_goods[1] = int(goods_num) if goods_num else se_goods[1]
                se_goods[2] = int(goods_select) if goods_select else se_goods[2]
        request.session['goods'] = session_goods

        return JsonResponse({'code': 200, 'msg': '请求成功'})


def del_cart(request, id):
    if request.method == 'POST':
        # 思路：通过传入的商品id值，去session中查找，查找到则删除数据
        session_goods = request.session.get('goods')
        for se_goods in session_goods:
            # se_goods:[goods_id, num, is_selelct]
            if se_goods[0] == id:
                session_goods.remove(se_goods)
                break
        request.session['goods'] = session_goods
        user_id = request.session.get('user_id')
        if user_id:
            # 删除数据库
            ShoppingCart.objects.filter(goods_id=id,
                                        user_id=user_id).delete()
        return JsonResponse({'code': 200, 'msg': '请求成功'})

        pass

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title%}
        {% endblock%}
    </title>
    {% block css%}
    {% endblock%}

    {% block js1%}
    {% endblock%}

</head>
<body>
{% block header%}
{% endblock%}

{% block search%}
{% endblock%}

{% block content%}
{% endblock%}

{% block footer%}
{% endblock %}

{% block js2%}
{% endblock%}
</body>
</html>

templates/base_main.html
{% extends 'base.html'%}

{% block css%}
{% load static %}
<link rel="stylesheet" type="text/css" href="{%static 'css/reset.css'%}">
<link rel="stylesheet" type="text/css" href="{%static 'css/main.css'%}">
{% endblock%}


{% block js1%}
<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock%}

{% block header%}
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到天天生鲜!</div>
        <div class="fr">
            {% if user.id%}
            <div class="login_info fl" style="display:block">
                欢迎您：<em>{{user.username}}</em>
                <a href="{%url 'user:logout'%}">退出</a>
            </div>
            {%else%}
            <div class="login_btn fl">
                <a href="{%url 'user:login'%}">登录</a>
                <span>|</span>
                <a href="{%url 'user:register'%}">注册</a>
            </div>
            {% endif%}
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'user:user_info'%}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:cart'%}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'order:user_order'%}">我的订单</a>
            </div>
        </div>
    </div>
</div>
{% endblock%}


{% block search%}

<div class="search_bar clearfix">
    <a href="{% url 'goods:index'%}" class="logo fl"><img src="/static/images/logo.png"></a>
    <div class="search_con fl">
        <input type="text" id="my_button1" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button"  id="my_button2" class="input_btn fr" onclick="my_value()" name="" value="搜索" >
    </div>
    <div class="guest_cart fr">
        <a href="{% url 'cart:cart' %}" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">0</div>
    </div>
    <script>
    function my_value(){
         my_text=$('#my_button1').val()
         location.href = '{% url 'goods:goods_search'%}?word='+my_text
       }
</script>
    <script>
        function cart_count(){
        $.get('/cart/cart_num/',function(data){
            if(data.code == '200'){
                $('#show_count').text(data.count)
            }
        })
        }
        cart_count()
    </script>
</div>
{% endblock%}

{% block footer%}
<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888 京ICP备*******8号</p>
</div>
{%endblock%}

templates/index.html
{% extends 'base_main.html'%}
{% block title%}
天天生鲜-首页
{% endblock%}

{% block js1%}
{{block.super}}
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
	<script type="text/javascript" src="/static/js/slide.js"></script>
{% endblock%}

{% block content%}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
			<li><a href="#model01" class="fruit">新鲜水果</a></li>
			<li><a href="#model02" class="seafood">海鲜水产</a></li>
			<li><a href="#model03" class="meet">猪牛羊肉</a></li>
			<li><a href="#model04" class="egg">禽类蛋品</a></li>
			<li><a href="#model05" class="vegetables">新鲜蔬菜</a></li>
			<li><a href="#model06" class="ice">速冻食品</a></li>
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
				<li><img src="/static/images/slide.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide02.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide03.jpg" alt="幻灯片"></li>
				<li><img src="/static/images/slide04.jpg" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
			<a href="#"><img src="/static/images/adv01.jpg"></a>
			<a href="#"><img src="/static/images/adv02.jpg"></a>
		</div>
	</div>

	{% for category in categorys %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{category.id}}">{{category.get_category_type_display}}</h3>
			<!--<div class="subtitle fl">-->
				<!--<span>|</span>-->
				<!--<a href="#">鲜芒</a>-->
				<!--<a href="#">加州提子</a>-->
				<!--<a href="#">亚马逊牛油果</a>-->
			<!--</div>-->
			<a href="{% url 'goods:my_list' category.id%}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="/media/{{category.category_front_image}}"></div>
			<ul class="goods_list fl">
				{%for goods in category.goods_set.all%}
				{% if forloop.counter <= 4%}
				<li>
					<h4><a href="{%url 'goods:detail' goods.id%}">{{goods.name}}</a></h4>
					<a href="{%url 'goods:detail' goods.id%}"><img src="/media/{{goods.goods_front_image}}"></a>
					<div class="prize">¥{{goods.market_price}}</div>
				</li>
				{% endif%}
				{%endfor%}
			</ul>
		</div>
	</div>
	{% endfor %}

	{% endblock%}
	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>

templates/list.html
{% extends 'base_main.html'%}
{% block title%}
天天生鲜-商品列表
{% endblock%}
{% block header%}
{% endblock%}

{% block content%}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                <li><a href="#" class="fruit">新鲜水果</a></li>
                <li><a href="#" class="seafood">海鲜水产</a></li>
                <li><a href="#" class="meet">猪牛羊肉</a></li>
                <li><a href="#" class="egg">禽类蛋品</a></li>
                <li><a href="#" class="vegetables">新鲜蔬菜</a></li>
                <li><a href="#" class="ice">速冻食品</a></li>
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

<div class="breadcrumb">
    <a href="#">全部分类</a>
    <span>></span>
    <a href="#">{{cate.get_category_type_display}}</a>
</div>

<div class="main_wrap clearfix">
    <div class="l_wrap fl clearfix">
        <div class="new_goods">
            <h3>新品推荐</h3>
            <ul>
                <li>
                    <a href="#"><img src="/static/images/goods/goods001.jpg"></a>
                    <h4><a href="#">进口柠檬</a></h4>
                    <div class="prize">￥3.90</div>
                </li>
                <li>
                    <a href="#"><img src="/static/images/goods/goods002.jpg"></a>
                    <h4><a href="#">玫瑰香葡萄</a></h4>
                    <div class="prize">￥16.80</div>
                </li>
            </ul>
        </div>
    </div>

    <div class="r_wrap fr clearfix">
        <div class="sort_bar">
            <a href="#" class="active">默认</a>
            <a href="#">价格</a>
            <a href="#">人气</a>
        </div>

        <ul class="goods_type_list clearfix">
            {% for goods in all_goods%}
            <li>
                <a href="{% url 'goods:detail' goods.id%}"><img src="/media/{{goods.goods_front_image}}"></a>
                <h4><a href="{% url 'goods:detail' goods.id%}">{{goods.name}}</a></h4>
                <div class="operate">
                    <span class="prize">￥{{goods.market_price}}</span>
                    <span class="unit">{{goods.market_price}}/500g</span>
                    <a href="#" class="add_goods" title="加入购物车"></a>
                </div>
            </li>
            {% endfor%}
        </ul>

        <div class="pagenation">
            console.log(id)
            {%if all_goods.has_previous%}
            <a href="{%url 'goods:my_list' my_id%}?page=all_goods.previous_page_number">上一页</a>
            {%else%}
            <a href="#">上一页</a>
            {%endif%}

            {% for i in all_goods.paginator.page_range %}
            <a href="{% url 'goods:my_list' my_id%}?page={{i}}">{{i}}</a>
            {% endfor %}

            {%if all_goods.has_next %}
            <a href="{%url 'goods:my_list' my_id%}?page=all_goods.next_page_number">上一页</a>
            {%else%}
            <a href="#">上一页</a>
            {%endif%}

        </div>
    </div>
</div>
{% endblock%}
{% block footer%}
{% endblock%}

templates/login.html
{% extends 'base_main.html'%}
{% block title%}
天天生鲜-登录
{% endblock %}

{% block js1%}
{%endblock%}

{% block header%}
{% endblock%}
{% block search%}
{% endblock%}

{% block content%}
<body>
<div class="login_top clearfix">
    <a href="index.html" class="login_logo"><img src="/static/images/logo02.png"></a>
</div>

<div class="login_form_bg">
    <div class="login_form_wrap clearfix">
        <div class="login_banner fl"></div>
        <div class="slogan fl">日夜兼程 · 急速送达</div>
        <div class="login_form fr">
            <div class="login_title clearfix">
                <h1>用户登录</h1>
                <a href="{% url 'user:register'%}">立即注册</a>
            </div>
            <div class="form_input">
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="text" name="username" class="name_input" placeholder="请输入用户名">
                    <div class="user_error" style="display:block">{{errors.username}}</div>
                    <input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
                    <div class="pwd_error" style="display:block">{{errors.pwd}}</div>
                    <input type="submit"  value="登录" class="input_submit">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock%}

templates/user_center_info.html
{% extends 'base_main.html'%}
{%block title%}天天生鲜-用户中心
{% endblock%}

{% block search%}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" id="my_button1" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" onclick="my_value()" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
    <script>
    function my_value(){
    	 my_text=$('#my_button1').val()
         location.href = '{% url 'goods:goods_search'%}?word='+my_text
       }
</script>
{% endblock%}

{% block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{%url 'user:user_info'%}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'order:user_order'%}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_site'%}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{user.username}}</li>
							<li><span>联系方式：</span>18210569700</li>
							<li><span>联系地址：</span>北京市昌平区</li>			
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
			<div class="has_view_list">
					<ul class="goods_type_list clearfix">
				{% for val in recent_goods%}
				<li>
					<a href="{%url 'goods:detail' val.goods_id_id%}"><img src="/media/{{val.goods_id.goods_front_image}}"></a>
					<h4><a href="detail.html">{{val.goods_id.name}}</a></h4>
					<div class="operate">
						<span class="prize">￥{{val.goods_id.market_price}}</span>
						<span class="unit">{{val.goods_id.market_price}}/500g</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
				{% endfor%}
			</ul>
		</div>
		</div>
	</div>
{%endblock%}

templates/user_center_order.html
{% extends 'base_main.html'%}

{%block title%}
天天生鲜-用户中心
{% endblock %}

{% block search%}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" id="my_button1" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" onclick="my_value()" class="input_btn fr" name="" value="搜索">
		</div>		
	</div>
    <script>
    function my_value(){
    	 my_text=$('#my_button1').val()
         location.href = '{% url 'goods:goods_search'%}?word='+my_text
       }
	</script>
{% endblock%}

{% block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{%url 'user:user_info'%}">· 个人信息</a></li>
				<li><a href="{% url 'order:user_order'%}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:user_site'%}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
			{% for order in orders%}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.add_time}}</li>
					<li class="col02" style="width:55%">订单号:{{order.order_sn}}</li>
					<li class="col02 stress">{{order.get_pay_status_display}}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
								{%for order_goods in order.goods.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="/media/{{order_goods.goods.goods_front_image}}"></li>
									<li class="col02">{{order_goods.goods.name}}<em>{{order_goods.goods.market_price}}/500g</em></li>
									<li class="col03">{{order_goods.goods_nums}}</li>
									<li class="col04">{{order_goods.goods.market_price}}元</li>
								</ul>
								{%endfor%}
							</td>
							<td width="15%">{{order.order_mount}}元</td>
							<td width="15%">{{order.get_pay_status_display}}</td>
							<td width="15%"><a href="#" class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				{%endfor%}

				<div class="pagenation">
					{% if orders.has_previous%}
					<a href="{% url 'order:user_order'%}?page={{orders.previous_page_number}}">上一页</a>
					{%else%}
					<a href="#">上一页</a>
					{% endif%}

					{% for i in orders.paginator.page_range%}

					<a href="{% url 'order:user_order'%}?page={{i}}">{{i}}</a>

					{% endfor%}


					{% if orders.has_next%}
					<a href="{% url 'order:user_order'%}?page={{orders.next_page_number}}">下一页</a>
					{%else%}
					<a href="#">下一页</a>
					{% endif%}
				</div>
		</div>
	</div>
{% endblock%}

templates/user_center_site.html
{% extends 'base_main.html'%}
{% block title%}天天生鲜-用户中心
{% endblock%}
{% block search%}
<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" id="my_button1" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" onclick="my_value()" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
    <script>
    function my_value(){
    	 my_text=$('#my_button1').val()
         location.href = '{% url 'goods:goods_search'%}?word='+my_text
       }
	</script>
{% endblock%}
{% block content%}
	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{%url 'user:user_info'%}">· 个人信息</a></li>
				<li><a href="{% url 'order:user_order'%}">· 全部订单</a></li>
				<li><a href="{% url 'user:user_site'%}" class="active">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">收货地址</h3>
				<div class="site_con">
					<dl>
						<dt>当前地址：</dt>
						<dd>北京市 海淀区 东北旺西路8号中关村软件园 （李思 收） 182****7528</dd>
						{%for address in user_address%}
							<dd>{{address.address}} ({{address.signer_name}} 收)  {{address.signer_mobile}}</dd>
						{% endfor%}
					</dl>
				</div>
				<h3 class="common_title2">编辑地址</h3>
				<div class="site_con">
					<form action="" method="post">
						{% csrf_token%}
						<div class="form_group">
							<label>收件人：</label>
							<input type="text" name="username">
							{{errors.username}}
						</div>
						<div class="form_group form_group2">
							<label>详细地址：</label>
							<textarea class="site_area" name="address"></textarea>
							{{errors.address}}
						</div>
						<div class="form_group">
							<label>邮编：</label>
							<input type="text" name="postcode">
							{{errors.postcode}}
						</div>
						<div class="form_group">
							<label>手机：</label>
							<input type="text" name="tel">
							{{errors.tel}}
						</div>

						<input type="submit" value="提交" class="info_submit">
					</form>
				</div>
		</div>
	</div>
{% endblock%}

{% block footer%}


{% endblock%}